services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres -U postgres']
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - stock:/var/lib/postgresql/data

  stock:
    image: deutschemodelunitednations/munify-stock:latest
    depends_on:
      - postgres
    ports:
      - 3000:3000

    # for config options, please refer to the 'src/lib/config' directory
    # for server/proxy config options, please refer to https://svelte.dev/docs/kit/adapter-node#Environment-variables-PORT-HOST-and-SOCKET_PATH
    environment:
      # - PORT=3000
      # - HOST=0.0.0.0
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      # change this to where the app is located at. E.g. https://stock.munify.cloud
      - ORIGIN=https://{your origin}

      # variables which are exposed to the client must be prefixed with PUBLIC_
      - PUBLIC_LOGTO_ENDPOINT=https://your-logto-instance.logto.app
      - PUBLIC_LOGTO_APP_ID=your-app-id
      - LOGTO_APP_SECRET=your-app-secret
      - LOGTO_COOKIE_ENCRYPTION_KEY=a-random-string-at-least-32-characters
      #
      # Please make sure that your Logto application allows
      #
      # https://{your origin}/callback
      #
      # as a redirect URI, and
      #
      # https://{your origin}/
      #
      # as a post sign-out redirect URI.

    # if you would like to disable the database migrations, you can use the following command instead
    # command: node ./index.js

volumes:
  stock:
